### PR TITLE
Composer support right way

### PR DESCRIPTION
**Pull request by MASNathan**
You probably don't need it, but it's Hacktober Fest :+1:

### CODE REVIEW

**Comment by DanielRuf** [comment]
Nice 👍

**Comment by Maikuolan** [comment]
Looks good! And thanks for the contribution. :+1: 😊

A couple of notes:
- The reason for the decreased code quality rating with SensioLabsInsight is because of the helper function, I think. Due to that it is a global function in the global namespace, and SensioLabsInsight doesn't like those, but that's okay. I can adjust the settings for that anyway.
- Short array syntax (using `$Arr = [];` instead of `$Arr = array();`) was [introduced with PHP 5.4.0](http://php.net/manual/en/migration54.new-features.php), meaning that using short array syntax would prevent the class from being used with older PHP versions. This won't be a problem for us though, because the project (as per mentioned by `composer.json`) is currently locked to PHP >= 5.4.0 anyway, but it does also mean that downgrading the PHPUnit version (`3cc8b05`) in order to be compatible with PHP 5.3.0 isn't really necessary either (AFAIK). I'm somewhat of an amateur with PHPUnit though, so as to which version would be best to use? TBH, I don't know. '^^

The help is much appreciated. I'll pull this into master in a few minutes. :-)

**Comment by MASNathan** [comment]
I was looking at the PHP version requirements of PHPUnit and here is the TL;DR version:

|PHPUnit Version|PHP Version|
|---|---|
|>=4.8|>=5.3.3|
|>=5.0|>=5.6|

Packagist: [phpunit/phpunit](https://packagist.org/packages/phpunit/phpunit#4.8.36)

So, since we need at least PHP 5.4 support, the best choice is PHPUnit >=4.8

**Comment by Maikuolan** [comment]
Cheers; Sounds good. :+1:

**Pull request merged**
